# Generated by Django 5.0.1 on 2024-01-25 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('poster', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg'])])),
                ('bg_picture', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg'])])),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('mpa_rating', models.CharField(blank=True, choices=[('g', 'G'), ('pg', 'PG'), ('pg-13', 'PG-13'), ('r', 'R'), ('nc-17', 'NC-17')], max_length=10, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='acted_movies', to='person.person')),
                ('directors', models.ManyToManyField(blank=True, related_name='directed_movies', to='person.person')),
                ('genres', models.ManyToManyField(blank=True, to='genre.genre')),
                ('writers', models.ManyToManyField(blank=True, related_name='written_movies', to='person.person')),
            ],
        ),
    ]
