# Generated by Django 5.0.1 on 2024-01-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='stars',
        ),
    ]
